# Praktikum 2: Komputasi Numerik dengan NumPy Array

<a href="https://colab.research.google.com/github/pakizhan-ump/ml-umpontianak/blob/main/Modules/Week-02/Praktikum-02/Praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Tujuan Praktikum
Mahasiswa mampu menggunakan library **NumPy** untuk membuat dan memanipulasi array multidimensi serta memahami keunggulannya dibandingkan List untuk komputasi numerik.

## 📖 Dasar Teori
**NumPy (Numerical Python)** adalah library fundamental untuk komputasi ilmiah di Python. Struktur data utamanya adalah **ndarray (n-dimensional array)**, yang dirancang khusus untuk operasi numerik yang efisien. Keunggulan utamanya meliputi:
* **Homogeneous:** Semua elemen dalam sebuah array harus memiliki tipe data yang sama (misalnya, semua `float64` atau semua `int32`), yang memungkinkan penyimpanan memori yang lebih efisien.
* **Ukuran Tetap:** Ukuran array ditentukan saat pembuatan, membuatnya lebih dapat diprediksi dalam hal alokasi memori.
* **Efisiensi Memori & Kecepatan:** Operasi matematika pada NumPy array jauh lebih cepat karena dieksekusi oleh kode C yang terkompilasi, bukan melalui interpreter Python.
* **Mendukung Operasi Vektorisasi:** Memungkinkan operasi matematika dilakukan pada seluruh elemen array secara bersamaan tanpa perlu menulis *loop* `for`, membuat kode lebih ringkas dan cepat.

Dalam machine learning, data seperti gambar (matriks piksel), sinyal audio, atau fitur-fitur numerik hampir selalu direpresentasikan sebagai NumPy array.

In [3]:
import numpy as np

# 🔧 OPERASI FUNDAMENTAL NUMPY

# 1. ARRAY CREATION & TYPES

In [4]:
print("=== ARRAY CREATION ===")
arr1d = np.array([1, 2, 3, 4, 5])                    # 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])            # 2D array
arr3d = np.random.rand(2, 3, 4)                     # 3D random array

print("1D array shape:", arr1d.shape)
print("2D array shape:", arr2d.shape)
print("3D array shape:", arr3d.shape)

=== ARRAY CREATION ===
1D array shape: (5,)
2D array shape: (2, 3)
3D array shape: (2, 3, 4)


# 2. DATA TYPES

In [5]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_bool = np.array([True, False, True])

print("Data types:")
print("arr_int dtype:", arr_int.dtype)
print("arr_float dtype:", arr_float.dtype)

Data types:
arr_int dtype: int32
arr_float dtype: float64


# 3. ACCESS & SLICING

In [6]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("\n=== ACCESS & SLICING ===")
print("Element [1,2]:", matrix[1, 2])                # Single element
print("Row 1:", matrix[1, :])                        # Entire row
print("Column 2:", matrix[:, 2])                     # Entire column
print("Submatrix 2x2:\n", matrix[0:2, 1:3])          # Submatrix
print("Every other row:\n", matrix[::2, :])          # Step slicing


=== ACCESS & SLICING ===
Element [1,2]: 7
Row 1: [5 6 7 8]
Column 2: [ 3  7 11]
Submatrix 2x2:
 [[2 3]
 [6 7]]
Every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


# 4. RESHAPING

In [7]:
print("\n=== RESHAPING ===")
arr = np.arange(12)                                  # 0-11
print("Original shape:", arr.shape)
reshaped = arr.reshape(3, 4)                        # Reshape to 3x4
flattened = reshaped.flatten()                      # Back to 1D
transposed = reshaped.T                             # Transpose

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: (12,)
Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed 4x3:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


# 5. MATHEMATICAL OPERATIONS

In [8]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)                             # Element-wise add
print("a * b =", a * b)                             # Element-wise multiply
print("a ** 2 =", a ** 2)                           # Power
print("np.dot(a, b) =", np.dot(a, b))               # Dot product


=== MATHEMATICAL OPERATIONS ===
a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]
np.dot(a, b) = 32


# 6. AGGREGATION

In [9]:
print("\n=== AGGREGATION ===")
data = np.random.rand(5, 4)                         # 5x4 random data
print("Data:\n", data)
print("Sum all:", np.sum(data))
print("Mean all:", np.mean(data))
print("Std all:", np.std(data))
print("Sum columns:", np.sum(data, axis=0))         # Along columns
print("Mean rows:", np.mean(data, axis=1))          # Along rows


=== AGGREGATION ===
Data:
 [[0.11089082 0.4393365  0.2017192  0.8957636 ]
 [0.47537022 0.56327557 0.69551609 0.13933145]
 [0.60441738 0.53984109 0.20306122 0.94285357]
 [0.59886547 0.69478493 0.88046784 0.62435405]
 [0.29563369 0.10549426 0.45653457 0.21844044]]
Sum all: 9.685951962594277
Mean all: 0.48429759812971385
Std all: 0.25999582747954114
Sum columns: [2.08517758 2.34273236 2.43729892 2.82074311]
Mean rows: [0.41192753 0.46837333 0.57254332 0.69961807 0.26902574]


# 7. BROADCASTING

In [10]:
print("\n=== BROADCASTING ===")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix + Vector:\n", result)


=== BROADCASTING ===
Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


# 8. RANDOM OPERATIONS

In [11]:
print("\n=== RANDOM OPERATIONS ===")
random_arr = np.random.rand(3, 3)                   # Uniform [0,1)
normal_arr = np.random.randn(3, 3)                  # Normal distribution
integers = np.random.randint(0, 100, (3, 3))        # Random integers

print("Uniform random:\n", random_arr)
print("Normal random:\n", normal_arr)
print("Random integers:\n", integers)


=== RANDOM OPERATIONS ===
Uniform random:
 [[4.16509948e-01 8.83280259e-01 3.24345021e-01]
 [1.22087955e-01 3.56297838e-01 9.06828442e-01]
 [2.72132249e-01 6.47690121e-01 5.20376995e-04]]
Normal random:
 [[-1.34938997 -1.01907279  0.12701224]
 [-1.24944372  1.94511561 -0.15333646]
 [-0.90698723 -0.81735416 -0.48312268]]
Random integers:
 [[87 51 61]
 [57 51 11]
 [38  1  2]]


# 9. SPLITTING & JOINING

In [12]:
print("\n=== SPLITTING & JOINING ===")
arr = np.arange(12).reshape(3, 4)
sub_arrays = np.split(arr, 3, axis=0)               # Split along rows
print("Original:\n", arr)
print("After split:")
for i, sub in enumerate(sub_arrays):
    print(f"Part {i}:\n{sub}")

# Joining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
joined = np.concatenate([arr1, arr2], axis=0)       # Vertical join
print("After concatenation:\n", joined)


=== SPLITTING & JOINING ===
Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After split:
Part 0:
[[0 1 2 3]]
Part 1:
[[4 5 6 7]]
Part 2:
[[ 8  9 10 11]]
After concatenation:
 [[1 2]
 [3 4]
 [5 6]]


# 10. CONDITIONAL OPERATIONS

In [13]:
print("\n=== CONDITIONAL OPERATIONS ===")
data = np.array([10, 25, 30, 45, 50, 65])
mask = data > 30                                    # Boolean mask
filtered = data[mask]                               # Filter with mask
print("Data > 30:", filtered)

# Where operation
result = np.where(data > 30, data, 0)               # Replace conditionally
print("Where > 30 else 0:", result)


=== CONDITIONAL OPERATIONS ===
Data > 30: [45 50 65]
Where > 30 else 0: [ 0  0  0 45 50 65]


# 🏋️ LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

### DATA PREPROCESSING DENGAN NUMPY ###

In [14]:

import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    # Cegah pembagian nol
    std[std == 0] = 1
    return (data - mean) / std

X_normalized = z_score_normalization(X)

# TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    lower = mean - std_threshold * std
    upper = mean + std_threshold * std
    return np.clip(data, lower, upper)

X_cleaned = handle_outliers(X_normalized)

# TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    num_classes = np.max(labels) + 1
    one_hot = np.zeros((labels.size, num_classes), dtype=int)
    one_hot[np.arange(labels.size), labels] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2, seed=42):
    np.random.seed(seed)
    n_samples = X.shape[0]
    indices = np.random.permutation(n_samples)
    test_size = int(n_samples * test_size)

    test_idx = indices[:test_size]
    train_idx = indices[test_size:]

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# Validasi
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed")

# Cek hasil ringkasan
print("\n--- Hasil Latihan 2 ---")
print("Z-score Normalized Shape:", X_normalized.shape)
print("Cleaned Data Shape:", X_cleaned.shape)
print("One-hot Encoding:\n", one_hot_labels)
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)


✅ NumPy operations completed

--- Hasil Latihan 2 ---
Z-score Normalized Shape: (100, 5)
Cleaned Data Shape: (100, 5)
One-hot Encoding:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]
Train shape: (80, 5) Test shape: (20, 5)
